#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _ampa_reg(void);
extern void _Cad_reg(void);
extern void _CaDynamics_E2_reg(void);
extern void _cadyn_reg(void);
extern void _Ca_HVA_reg(void);
extern void _ca_reg(void);
extern void _canin_reg(void);
extern void _CaT_reg(void);
extern void _gabaa_reg(void);
extern void _gabab_reg(void);
extern void _Gfluctp_reg(void);
extern void _glutamate_reg(void);
extern void _hin_reg(void);
extern void _h_kole_reg(void);
extern void _h_migliore_reg(void);
extern void _Ih_reg(void);
extern void _IKsin_reg(void);
extern void _IL_reg(void);
extern void _kadist_reg(void);
extern void _kapin_reg(void);
extern void _kaprox_reg(void);
extern void _kBK_reg(void);
extern void _kctin_reg(void);
extern void _kdrin_reg(void);
extern void _kv_reg(void);
extern void _MyExp2SynBB_reg(void);
extern void _nafx_reg(void);
extern void _na_reg(void);
extern void _NMDAeee_reg(void);
extern void _NMDAmajor_reg(void);
extern void _NMDA_reg(void);
extern void _PlateauConductance_reg(void);
extern void _SK_E2_reg(void);
extern void _vecstim_reg(void);
extern void _vmax_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," ampa.mod");
    fprintf(stderr," Cad.mod");
    fprintf(stderr," CaDynamics_E2.mod");
    fprintf(stderr," cadyn.mod");
    fprintf(stderr," Ca_HVA.mod");
    fprintf(stderr," ca.mod");
    fprintf(stderr," canin.mod");
    fprintf(stderr," CaT.mod");
    fprintf(stderr," gabaa.mod");
    fprintf(stderr," gabab.mod");
    fprintf(stderr," Gfluctp.mod");
    fprintf(stderr," glutamate.mod");
    fprintf(stderr," hin.mod");
    fprintf(stderr," h_kole.mod");
    fprintf(stderr," h_migliore.mod");
    fprintf(stderr," Ih.mod");
    fprintf(stderr," IKsin.mod");
    fprintf(stderr," IL.mod");
    fprintf(stderr," kadist.mod");
    fprintf(stderr," kapin.mod");
    fprintf(stderr," kaprox.mod");
    fprintf(stderr," kBK.mod");
    fprintf(stderr," kctin.mod");
    fprintf(stderr," kdrin.mod");
    fprintf(stderr," kv.mod");
    fprintf(stderr," MyExp2SynBB.mod");
    fprintf(stderr," nafx.mod");
    fprintf(stderr," na.mod");
    fprintf(stderr," NMDAeee.mod");
    fprintf(stderr," NMDAmajor.mod");
    fprintf(stderr," NMDA.mod");
    fprintf(stderr," PlateauConductance.mod");
    fprintf(stderr," SK_E2.mod");
    fprintf(stderr," vecstim.mod");
    fprintf(stderr," vmax.mod");
    fprintf(stderr, "\n");
  }
  _ampa_reg();
  _Cad_reg();
  _CaDynamics_E2_reg();
  _cadyn_reg();
  _Ca_HVA_reg();
  _ca_reg();
  _canin_reg();
  _CaT_reg();
  _gabaa_reg();
  _gabab_reg();
  _Gfluctp_reg();
  _glutamate_reg();
  _hin_reg();
  _h_kole_reg();
  _h_migliore_reg();
  _Ih_reg();
  _IKsin_reg();
  _IL_reg();
  _kadist_reg();
  _kapin_reg();
  _kaprox_reg();
  _kBK_reg();
  _kctin_reg();
  _kdrin_reg();
  _kv_reg();
  _MyExp2SynBB_reg();
  _nafx_reg();
  _na_reg();
  _NMDAeee_reg();
  _NMDAmajor_reg();
  _NMDA_reg();
  _PlateauConductance_reg();
  _SK_E2_reg();
  _vecstim_reg();
  _vmax_reg();
}
